const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../src/core/photo-pro'),G=require('../src/core/generator'),C=require('../src/core/plate-codec');
const image=fn=>({width:225,height:165,pixels:Array.from({length:37125},(_,i)=>Math.round(fn(i%225,Math.floor(i/225))))});
const recipe=im=>({version:1,mode:'photo',seed:77,layoutSeed:77,variation:0,params:{...G.defaults},image:im,pro:{version:1,...P.defaults,edits:[]}});
test('tone correction preserves luminance order including extreme shadow compression',()=>{for(const exposure of [0,50,100])for(const shadows of [0,50,100]){let last=-1;for(let i=0;i<256;i++){const v=P.value(i,{exposure,shadows});assert.ok(v>=last);last=v;}assert.equal(last,255);}});
test('adaptive image maze is repeatable and passages do not cross strong tone edges',()=>{const im=image((x,y)=>x<100?30:x<150?200:255),a=P.imageMaze(im,23);assert.deepEqual(a,P.imageMaze(im,23));assert.ok(a.regions.length>42);for(const r of a.regions)for(const [i,j]of r.edges){assert.ok(Math.abs(r.tones[i]-r.tones[j])<.18);assert.ok(r.tones[i]<.92&&r.tones[j]<.92);}});
test('local white, direction and frozen protection preserve distant geometry',()=>{const near={width:1,points:[[80,100],[95,110],[100,100],[110,90],[120,100]]},far={width:1,points:[[300,300],[350,350]]},e={type:'white',x:100,y:100,radius:18,angle:0};const a=P.applyEdits([near,far],[e]);assert.ok(a.includes(far));for(const p of a)for(const q of p.points)assert.ok(Math.hypot(q[0]-100,q[1]-100)>=18);const d=P.applyEdits([near,far],[{...e,type:'direction'}]);assert.equal(d[1],far);assert.notDeepEqual(d[0],near);const frozen=P.freeze([near],e),protectedResult=P.applyEdits([far],[{...e,type:'protect',frozen}]);assert.deepEqual(protectedResult.slice(1),frozen);});
test('layer switches and independent maze seed preserve flow geometry and JSON reproducibility',()=>{const r=recipe(image((x,y)=>40+170*x/225));r.pro.maze=50;const a=G.generate(r),b=G.generate({...r,pro:{...r.pro,mazeSeed:5}});assert.deepEqual(a.paths.filter(p=>p.role!=='maze'),b.paths.filter(p=>p.role!=='maze'));assert.notDeepEqual(a.paths.filter(p=>p.role==='maze'),b.paths.filter(p=>p.role==='maze'));assert.deepEqual(a,G.generate(JSON.parse(JSON.stringify(r))));const off=G.generate({...r,pro:{...r.pro,maze:0,contour:0}});assert.ok(off.paths.every(p=>p.role==='hatch'||p.role==='cross'));});
test('compact high-resolution plate codec is lossless and rejects corrupt data',()=>{const n=3000*2200,d=new Float32Array(n);d[0]=.123;d[n-1]=1;const encoded=C.encode(d),decoded=C.decode(encoded,Float32Array,n);assert.equal(decoded[0],d[0]);assert.equal(decoded[n-1],1);assert.throws(()=>C.decode(encoded.slice(1),Float32Array,n));assert.throws(()=>C.decode(C.encode(Float32Array.of(NaN)),Float32Array,1));});
test('six synthetic subject baselines remain finite and deterministic',()=>{
 const fixtures={portrait:(x,y)=>((x-112)/35)**2+((y-75)/50)**2<1?70+(x%8)*12:255,stillLife:(x,y)=>x>75&&x<140&&y>35&&y<135?50+x/2:245,plant:(x,y)=>Math.abs(x-112-22*Math.sin(y/12))<10?60:250,building:(x,y)=>x>40&&x<185&&y>30&&y<145?(x%22<8&&y%25<10?35:180):255,lowContrast:(x,y)=>220+20*Math.sin(x/18)*Math.cos(y/22),transparentWhite:(x,y)=>x>85&&x<135&&y>50&&y<120?100:255};
 for(const [name,fn]of Object.entries(fixtures)){const r=recipe(image(fn));if(name==='lowContrast')Object.assign(r.pro,P.autoLevels(r.image));const a=G.generate(r);assert.ok(a.paths.length,name);for(const p of a.paths)for(const q of p.points)assert.ok(q.every(Number.isFinite),name);assert.deepEqual(a.paths,G.generate(r).paths,name);}
});
test('five neutral tones have ordered engraving coverage before print overlap',()=>{let last=Infinity;for(const v of [30,75,120,165,210]){const a=G.generate(recipe(image(()=>v)));const area=a.paths.reduce((s,p)=>s+p.points.slice(1).reduce((n,q,i)=>n+Math.hypot(q[0]-p.points[i][0],q[1]-p.points[i][1])*p.width,0),0);assert.ok(area<last);last=area;}});
test('PNG export embeds physical pixel density',async()=>{const src=new Uint8Array(40),blob=await C.pngDpi(new Blob([src]),3000,254),out=new Uint8Array(await blob.arrayBuffer()),view=new DataView(out.buffer);assert.equal(String.fromCharCode(...out.slice(37,41)),'pHYs');assert.equal(view.getUint32(41),11811);assert.equal(out[49],1);});
test('engraving grammar makes short regional bundles and reserves cross layers for shadow',()=>{const im=image((x)=>x<112?225:35),curve=(x,role)=>({role,width:1,points:Array.from({length:80},(_,i)=>[x+i*.7,180+Math.sin(i/5)*9])});const styled=P.engravingGrammar([curve(80,'cross'),curve(520,'cross'),curve(520,'hatch')],im,19,{detail:65});assert.ok(styled.stats.bundles>2);assert.ok(styled.paths.every(p=>p.bundle));assert.ok(styled.paths.every(p=>p.points.length<=50));assert.ok(styled.paths.filter(p=>p.role==='cross').every(p=>p.points.reduce((s,q)=>s+q[0],0)/p.points.length>448));});
test('weak contours become lost-and-found while strong boundaries remain continuous',()=>{const flat=image(()=>150),edge=image(x=>x<112?30:230),weak={role:'contour',width:1,points:Array.from({length:120},(_,i)=>[100+i*2,200])},strong={role:'contour',width:1,points:Array.from({length:120},(_,i)=>[448,80+i*2])};const a=P.engravingGrammar([weak],flat,7),b=P.engravingGrammar([strong],edge,7);assert.ok(a.stats.lostContours>0);assert.ok(a.paths.reduce((n,p)=>n+p.points.length,0)<weak.points.length);assert.equal(b.stats.lostContours,0);assert.equal(b.paths.length,1);});
test('micro detail layer retains small alternating structures',()=>{const fine=image((x,y)=>x>50&&x<175&&y>35&&y<130?((x+y)%6<3?35:220):255),smooth=image(()=>180);const a=P.microDetails(fine,11,{detail:90}),b=P.microDetails(smooth,11,{detail:90});assert.ok(a.length>500);assert.equal(b.length,0);assert.ok(a.every(p=>p.mark==='micro-detail'&&p.points.length===3&&p.width<1&&p.points.every(([x,y])=>x>=24&&x<=876&&y>=24&&y<=636)));});
test('background hatching skips clean white and stops at strong subject boundaries',()=>{const white=image(()=>255),scene=image((x,y)=>x>85&&x<140&&y>45&&y<130?40:180);assert.equal(P.backgroundField(white,8,{detail:70}).length,0);const paths=P.backgroundField(scene,8,{detail:70});assert.ok(paths.length>10);assert.ok(paths.every(p=>p.mark==='background'));assert.ok(paths.every(p=>p.points.every(([x,y])=>!(x>340&&x<560&&y>180&&y<520))));});
test('dark masses appear only in the deepest tone tier',()=>{const deep=P.darkMasses(image(()=>15),4),middle=P.darkMasses(image(()=>90),4);assert.ok(deep.length>100);assert.equal(middle.length,0);assert.ok(deep.every(p=>p.mark==='dark-mass'&&p.width>.8));});
test('structure vocabulary distinguishes planes, curves and fragmented detail',()=>{const plane=image(()=>180),curve=image(x=>Math.max(0,Math.min(255,128+(x-112)*8))),fragment=image((x,y)=>(x+y)%2?20:235);assert.equal(P.structureKind(plane,450,330),'plane');assert.equal(P.structureKind(curve,450,330),'curve');assert.equal(P.structureKind(fragment,450,330),'fragment');});
