/* Full-reference engraving diagnostics. Scores are descriptive, not a trained aesthetic verdict. */
(function(root){
  'use strict';
  const clamp=x=>Math.max(0,Math.min(1,x));
  function raster(paths,w,h,filter=()=>true){const out=new Float32Array(w*h),sx=w/900,sy=h/660;for(const p of paths)if(filter(p))for(let j=1;j<p.points.length;j++){const a=p.points[j-1],b=p.points[j],x0=a[0]*sx,y0=a[1]*sy,x1=b[0]*sx,y1=b[1]*sy,n=Math.max(1,Math.ceil(Math.hypot(x1-x0,y1-y0)*2));for(let k=0;k<=n;k++){const x=Math.round(x0+(x1-x0)*k/n),y=Math.round(y0+(y1-y0)*k/n);if(x>=0&&x<w&&y>=0&&y<h)out[y*w+x]=Math.max(out[y*w+x],Math.min(1,(p.width||.5)*1.4));}}return out;}
  function edges(image){const {width:w,height:h,pixels:s}=image,g=new Float32Array(w*h),vals=[];for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,gx=-s[i-w-1]-2*s[i-1]-s[i+w-1]+s[i-w+1]+2*s[i+1]+s[i+w+1],gy=-s[i-w-1]-2*s[i-w]-s[i-w+1]+s[i+w-1]+2*s[i+w]+s[i+w+1],v=Math.hypot(gx,gy);g[i]=v;if(v>4)vals.push(v);}vals.sort((a,b)=>a-b);const threshold=vals.length?vals[Math.floor(vals.length*.68)]:Infinity,out=new Uint8Array(w*h);for(let i=0;i<g.length;i++)out[i]=g[i]>=threshold?1:0;return out;}
  function distance(mask,w,h){const d=new Float32Array(w*h);for(let i=0;i<d.length;i++)d[i]=mask[i]?0:1e4;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;if(x)d[i]=Math.min(d[i],d[i-1]+1);if(y)d[i]=Math.min(d[i],d[i-w]+1);if(x&&y)d[i]=Math.min(d[i],d[i-w-1]+1.414);}for(let y=h-1;y>=0;y--)for(let x=w-1;x>=0;x--){const i=y*w+x;if(x<w-1)d[i]=Math.min(d[i],d[i+1]+1);if(y<h-1)d[i]=Math.min(d[i],d[i+w]+1);if(x<w-1&&y<h-1)d[i]=Math.min(d[i],d[i+w+1]+1.414);}return d;}
  function match(a,b,w,h,tolerance){const db=distance(b,w,h);let hit=0,n=0;for(let i=0;i<a.length;i++)if(a[i]){n++;if(db[i]<=tolerance)hit++;}return n?hit/n:1;}
  function blur(src,w,h,r=3){const integral=new Float64Array((w+1)*(h+1)),out=new Float32Array(src.length);for(let y=0;y<h;y++){let row=0;for(let x=0;x<w;x++){row+=src[y*w+x];integral[(y+1)*(w+1)+x+1]=integral[y*(w+1)+x+1]+row;}}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const l=Math.max(0,x-r),rr=Math.min(w,x+r+1),t=Math.max(0,y-r),b=Math.min(h,y+r+1),sum=integral[b*(w+1)+rr]-integral[t*(w+1)+rr]-integral[b*(w+1)+l]+integral[t*(w+1)+l];out[y*w+x]=sum/((rr-l)*(b-t));}return out;}
  function correlation(a,b){let ma=0,mb=0;for(let i=0;i<a.length;i++){ma+=a[i];mb+=b[i];}ma/=a.length;mb/=b.length;let ab=0,aa=0,bb=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;ab+=x*y;aa+=x*x;bb+=y*y;}return aa&&bb?ab/Math.sqrt(aa*bb):0;}
  function evaluate(image,result,options={}){const w=image.width,h=image.height,reference=edges(image),contours=raster(result.paths,w,h,p=>p.role==='contour'||p.preserve),all=raster(result.paths,w,h),predicted=new Uint8Array(contours.length);for(let i=0;i<predicted.length;i++)predicted[i]=contours[i]>.05?1:0;const tolerance=options.tolerance??Math.max(1,Math.round(w/225*1.5)),precision=match(predicted,reference,w,h,tolerance),recall=match(reference,predicted,w,h,tolerance),f1=precision+recall?2*precision*recall/(precision+recall):0,ink=blur(all,w,h,Math.max(1,Math.round(w/225*3))),tone=new Float32Array(w*h);for(let i=0;i<tone.length;i++)tone[i]=1-image.pixels[i]/255;const toneCorrelation=clamp((correlation(tone,ink)+1)/2),bins=Array.from({length:5},()=>({ink:0,n:0}));for(let i=0;i<tone.length;i++){const b=Math.min(4,Math.floor(tone[i]*5));bins[b].ink+=ink[i];bins[b].n++;}const means=bins.map(b=>b.n?b.ink/b.n:0);let ordered=0,pairs=0;for(let i=1;i<5;i++)if(bins[i].n&&bins[i-1].n){pairs++;if(means[i]>=means[i-1])ordered++;}const structural=result.paths.filter(p=>!['micro-detail','dark-mass'].includes(p.mark)),short=structural.filter(p=>{let l=0;for(let i=1;i<p.points.length;i++)l+=Math.hypot(p.points[i][0]-p.points[i-1][0],p.points[i][1]-p.points[i-1][1]);return l<12;}).length,shortFragmentRate=structural.length?short/structural.length:0,white=[];for(let i=0;i<tone.length;i++)if(image.pixels[i]>242)white.push(ink[i]);const whiteInk=white.length?white.reduce((a,b)=>a+b,0)/white.length:0;return{contourPrecision:+precision.toFixed(4),contourRecall:+recall.toFixed(4),contourF1:+f1.toFixed(4),toneCorrelation:+toneCorrelation.toFixed(4),toneOrder:+(pairs?ordered/pairs:1).toFixed(4),whitePreservation:+clamp(1-whiteInk*3).toFixed(4),shortFragmentRate:+shortFragmentRate.toFixed(4),toneInkByBand:means.map(x=>+x.toFixed(4)),paths:result.paths.length};}
  const api={evaluate,raster,edges};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.QualityMetrics=api;
})(globalThis);
